/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewport', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'panel',
                flex: 2,
                html: 'This is MyPanel1',
                style: 'background-color: yellow'
            },
            {
                xtype: 'panel',
                flex: 1,
                html: 'This is MyPanel2',
                style: 'background-color: brown'
            }
        ]
    }

});