/*
 * File: app/model/Session.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RegistrationApp.model.Session', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'title'
        },
        {
            name: 'description'
        },
        {
            name: 'level'
        },
        {
            name: 'twitterHashTags'
        },
        {
            name: 'BoxFolderIdString'
        },
        {
            name: 'BoxFolderEmailInAddress'
        },
        {
            name: 'BoxFolderPublicUrl'
        },
        {
            name: 'approved'
        },
        {
            name: 'createDate'
        },
        {
            name: 'sessionLevel'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/rest/Session/'
    }
});