/*
 * File: app/store/JsonPStoreSessions.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.JsonPStoreSessions', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.SessionsModel'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.SessionsModel',
        storeId: 'JsonPStoreSessions',
        proxy: {
            type: 'jsonp',
            limitParam: '999',
            pageParam: '999',
            startParam: '0',
            url: 'http://www.siliconvalley-codecamp.com/SessionsJSONP.aspx',
            callbackKey: 'jsonp',
            reader: {
                type: 'json',
                idProperty: 'AttendeesId',
                rootProperty: 'rows'
            }
        }
    }
});