/*
 * File: app/view/AttendeeAfterLogin.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RegistrationApp.view.AttendeeAfterLogin', {
    extend: 'Ext.form.Panel',
    alias: 'widget.AttendeeAfterLoginAlias',

    id: 'attendeeAfterLoginProfileId',
    bodyPadding: 10,
    title: 'Attendee After Login',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'radiogroup',
                    padding: 5,
                    width: 400,
                    fieldLabel: '',
                    allowBlank: false,
                    columns: 1,
                    items: [
                        {
                            xtype: 'radiofield',
                            itemId: 'AttendingSaturdayAndSundayId',
                            name: 'attendingDaysChoiceCurrentYear',
                            boxLabel: 'Attending Saturday and Sunday',
                            checked: true,
                            inputValue: 'AttendingSaturdaySunday'
                        },
                        {
                            xtype: 'radiofield',
                            itemId: 'AttendingSaturdayId',
                            name: 'attendingDaysChoiceCurrentYear',
                            boxLabel: 'Attending Saturday',
                            inputValue: 'AttendingSaturday'
                        },
                        {
                            xtype: 'radiofield',
                            itemId: 'AttendingSundayId',
                            name: 'attendingDaysChoiceCurrentYear',
                            boxLabel: 'Attending Sunday',
                            inputValue: 'AttendingSunday'
                        },
                        {
                            xtype: 'radiofield',
                            itemId: 'AttendingNotSureDayYetId',
                            name: 'attendingDaysChoiceCurrentYear',
                            inputId: 'AttendingNotSureYetRb',
                            boxLabel: 'Not Sure Which Days Yet',
                            inputValue: 'AttendingNotSureDayYet'
                        },
                        {
                            xtype: 'radiofield',
                            itemId: 'NotAttendingThisYearId',
                            name: 'attendingDaysChoiceCurrentYear',
                            inputId: 'NotAttendingRb',
                            boxLabel: 'Can Not Make It This Year',
                            inputValue: 'NotAttendingThisYear'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'First Name',
                    name: 'userFirstName',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Last Name',
                    name: 'userLastName',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Company',
                    name: 'company'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Principle Job',
                    name: 'principleJob'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Email',
                    name: 'email',
                    allowBlank: false,
                    vtype: 'email'
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    fieldLabel: 'Volunteer',
                    name: 'volunteeredCurrentYear',
                    boxLabel: '(Volunter To Help Day Of)',
                    inputValue: 'true',
                    uncheckedValue: 'false'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Phone Number (If Volunteer)',
                    name: 'phoneNumber'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Twitter Handle',
                    name: 'twitterHandle'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Eventboard Email',
                    name: 'emailEventBoard'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'City',
                    name: 'city'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'State',
                    name: 'state'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Zipcode',
                    name: 'userZipCode'
                },
                {
                    xtype: 'fieldset',
                    title: 'Reset Password (Leave blank to not change password)',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Password',
                            name: 'password1'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Password Confirm',
                            name: 'password2'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    itemId: 'ToolBarAttendeeSpeaker',
                    layout: {
                        pack: 'end',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'logoutButtonId',
                            iconAlign: 'right',
                            text: 'Logout'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            disabled: true,
                            itemId: 'continueButtonId',
                            iconAlign: 'right',
                            text: 'Continue'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});