/*
 * File: app/view/SpeakerSessionUpdate.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RegistrationApp.view.SpeakerSessionUpdate', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.SpeakerSessionUpdateAlias',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    itemId: 'ToolBarAttendeeSpeaker',
                    layout: {
                        pack: 'end',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'sessionButtonSaveChangesId',
                            text: 'Save Changes'
                        },
                        {
                            xtype: 'button',
                            id: 'sessionButtonAddNewId',
                            text: 'Add New Session'
                        },
                        {
                            xtype: 'button',
                            id: 'SessionButtonDelete',
                            text: 'Delete Session'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'speakerSessionsBackButtonItemId',
                            iconAlign: 'right',
                            text: 'Back'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'continueButtonId',
                            iconAlign: 'right',
                            text: 'Continue'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 2,
                    region: 'north',
                    split: true,
                    id: 'sessionsBySpeakerGridPanelId',
                    padding: 5,
                    autoScroll: true,
                    animCollapse: true,
                    collapseDirection: 'top',
                    collapsible: false,
                    store: 'SessionStore',
                    viewConfig: {
                        border: 1
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'title',
                            text: 'Session Title',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            width: 50,
                            dataIndex: 'id',
                            text: 'Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            width: 50,
                            dataIndex: 'attendeeId',
                            text: 'attendeesId'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            width: 50,
                            dataIndex: 'sessionId',
                            text: 'sessionsId'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if (value == true) {
                                    return ''; // don't show anything if approved, just like old days
                                } else {
                                    return 'pending approval';
                                }

                            },
                            width: 200,
                            dataIndex: 'approved'
                        }
                    ],
                    listeners: {
                        selectionchange: {
                            fn: me.onSessionsBySpeakerGridPanelIdSelectionChange,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    flex: 7,
                    region: 'center',
                    disabled: true,
                    id: 'sessionDetailPanelId',
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'form',
                            flex: 5,
                            region: 'west',
                            split: true,
                            id: 'sessionFormPanelEditorId',
                            itemId: 'sessionFormPanelEditorItemId',
                            width: 150,
                            autoScroll: true,
                            bodyPadding: 10,
                            items: [
                                {
                                    xtype: 'fieldset',
                                    formBind: true,
                                    itemId: 'FieldSetSessionEditorItemId',
                                    title: 'Basic Session Information',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            width: 150,
                                            fieldLabel: 'Title',
                                            name: 'title',
                                            maxLength: 75
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            width: 150,
                                            fieldLabel: 'Hash Tags For Twitter',
                                            name: 'twitterHashTags'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            height: 100,
                                            fieldLabel: 'Session Description (just text, no html please)',
                                            name: 'description'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Session Level (Beginner, Intermediate or Advanced)',
                                            name: 'sessionLevel'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            hidden: true,
                                            fieldLabel: 'sessionId',
                                            name: 'sessionId'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            hidden: true,
                                            fieldLabel: 'attendeesId',
                                            name: 'id'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 2,
                            region: 'center',
                            id: 'SessionTagsGridPanelId',
                            autoScroll: true,
                            title: 'Session Tags For Selected Session',
                            store: 'TagStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 160,
                                    dataIndex: 'tagName',
                                    text: 'TagName',
                                    flex: 1
                                },
                                {
                                    xtype: 'booleancolumn',
                                    hidden: true,
                                    width: 60,
                                    dataIndex: 'taggedInSession',
                                    text: 'Tagged'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {
                                mode: 'SIMPLE',
                                showHeaderCheckbox: false,
                                listeners: {
                                    selectionchange: {
                                        fn: me.onCheckboxselectionmodelSelectionChange,
                                        scope: me
                                    },
                                    select: {
                                        fn: me.onCheckboxModelSelect,
                                        scope: me
                                    }
                                }
                            })
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onSessionsBySpeakerGridPanelIdSelectionChange: function(model, selected, eOpts) {
        if (selected.length > 0) {  // on delete, this fires and then there is nothing selected
            var sessionData = selected[0].getData();

            // get handle to bottom window containing form and tags to enable
            var sessionDetailPanel = Ext.getCmp('sessionDetailPanelId');
            sessionDetailPanel.setDisabled(false);


            // fill data into form for session info
            var panelForm = Ext.getCmp('sessionFormPanelEditorId').getForm();

            var myRec = Ext.create("RegistrationApp.model.Session",sessionData);
            panelForm.loadRecord(myRec);


            //panelForm.setValues(sessionData);

            // fill data in for tags
            var tagList = Ext.getCmp("SessionTagsGridPanelId");
            var tagListStore = tagList.store;
            tagListStore.load({
                params: {
                    sessionId: sessionData.id
                },
                callback: function(records,operation,success) {
                    // get selection model of grid
                    var sm = tagList.getSelectionModel();
                    var recs = [];
                    Ext.each(records,function(rec) {
                        if (rec.get("taggedInSession") === true) {
                            recs.push(rec);
                        }
                    });
                    sm.select(recs);



                    tagList.getView().scrollBy(0, -10000);

                    //tagList.scrollBy(0, -10000);
                    // sm.select(0);


                }
            });
        }





    },

    onCheckboxselectionmodelSelectionChange: function(model, selected, eOpts) {
        var tagListStore = model.getStore();

        // all records that are selected are passed in here.  we need to run through the store
        // itself and verify that is what we think we should have.
        var tagsSelected1 = [];
        Ext.each(selected,function(rec) {
            tagsSelected1.push(rec.getData().tagName); 
        });


        // find record in store and update it


        tagListStore.each(function(storeRec) {
            var storeRecTagName = storeRec.getData().tagName;
            var storeRecTaggedInSession = storeRec.getData().taggedInSession;
            var gridPanelTagged = Ext.Array.contains(tagsSelected1,storeRecTagName);

            if (storeRecTaggedInSession != gridPanelTagged) {
                storeRec.set("taggedInSession",gridPanelTagged);
            }
        });


    },

    onCheckboxModelSelect: function(rowmodel, record, index, eOpts) {

        var cnt = rowmodel.getSelection().length;
        if (cnt > 7) {
            Ext.Msg.alert("7 tags limit per session.  Please uncheck other tags before checking new ones (careful not to click on tagname, delects all, sorry)");
            var modelRec = rowmodel.getLastSelected();
            rowmodel.deselect(modelRec);
        }
    }

});