/*
 * File: app/view/SpeakerAfterLoginNotDup.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RegistrationApp.view.SpeakerAfterLoginNotDup', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.SpeakerAfterLoginAlias2',

    autoShow: false,
    id: 'speakerAfterLoginId',
    itemId: 'speakerAfterLogin',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 5,
                    region: 'west',
                    split: true,
                    id: 'SpeakerPanelDetailProfPictId',
                    width: 150,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'form',
                            flex: 4,
                            autoShow: false,
                            id: 'speakerAfterLoginProfileId',
                            itemId: '',
                            autoScroll: true,
                            defaults: {
                                anchor: '95%'
                            },
                            bodyPadding: 15,
                            title: 'Speaker After Login',
                            url: '/api/Register',
                            items: [
                                {
                                    xtype: 'radiogroup',
                                    name: 'CanSpeakDate',
                                    id: 'CanSpeakRbGroupId',
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    fieldLabel: '',
                                    allowBlank: false,
                                    blankText: 'You must choose which day(s) you can speak',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            flex: 1,
                                            itemId: 'speakSaturdayAndSundayId',
                                            name: 'attendingDaysChoiceCurrentYear',
                                            boxLabel: 'Can Speak Saturday Or Sunday',
                                            checked: true,
                                            inputValue: 'AttendingSaturdaySunday'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            itemId: 'speakSaturdayId',
                                            inputId: 'speakSaturday',
                                            name: 'attendingDaysChoiceCurrentYear',
                                            boxLabel: 'Can Speak Saturday',
                                            inputValue: 'AttendingSaturday'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            itemId: 'speakSundayId',
                                            name: 'attendingDaysChoiceCurrentYear',
                                            boxLabel: 'Can Speak Sunday',
                                            inputValue: 'AttendingSunday'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'userFirstName',
                                    fieldLabel: 'FirstName',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'userLastName',
                                    fieldLabel: 'Last Name',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'email',
                                    fieldLabel: 'Email',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'phoneNumber',
                                    fieldLabel: 'Phone Number'
                                },
                                {
                                    xtype: 'combobox',
                                    name: 'shirtSize',
                                    fieldLabel: 'Speaker Shirt Size',
                                    allowBlank: false,
                                    displayField: 'shirtSize',
                                    store: 'ShirtSizeStore',
                                    valueField: 'shirtSize'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'userWebsite',
                                    fieldLabel: 'Web Site'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'twitterHandle',
                                    fieldLabel: 'Twitter Handle'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'facebookId',
                                    fieldLabel: 'Facebook'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'googlePlusId',
                                    fieldLabel: 'Google Plus'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'linkedInId',
                                    fieldLabel: 'LinkedIn'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'emailEventBoard',
                                    fieldLabel: 'Eventboard Email'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'city',
                                    fieldLabel: 'City',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'state',
                                    fieldLabel: 'State',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'userZipCode',
                                    fieldLabel: 'Zipcode',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    hidden: true,
                                    name: 'attendeesId',
                                    fieldLabel: 'Attendees Id',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'volunteeredCurrentYear',
                                    fieldLabel: 'Volunteer',
                                    boxLabel: '(Volunteer To Help Day Of)',
                                    inputValue: 'true',
                                    uncheckedValue: 'false'
                                },
                                {
                                    xtype: 'textareafield',
                                    name: 'userBio',
                                    fieldLabel: 'Bio',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 500,
                                    minLength: 30
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    itemId: 'ToolBarAttendeeSpeaker',
                                    layout: {
                                        pack: 'end',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            disabled: false,
                                            itemId: 'logoutButtonId',
                                            iconAlign: 'right',
                                            text: 'Logout'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            formBind: true,
                                            disabled: false,
                                            itemId: 'continueButtonId',
                                            iconAlign: 'right',
                                            text: 'Continue'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 3,
                    region: 'center',
                    autoShow: true,
                    itemId: 'speakerSessionsId',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    collapsible: false,
                    title: 'Speaker Sessions',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Edit Selected Session'
                                },
                                {
                                    xtype: 'button',
                                    id: 'AddNewSessionButtonId',
                                    text: 'Add New Session'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 2,
                            id: 'sessionsBySpeakerGridPanelId',
                            store: 'StoreSessions',
                            viewConfig: {

                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'title',
                                    flex: 1,
                                    text: 'Title'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'id',
                                    text: 'Id'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            flex: 9,
                            id: 'speakerPictureUploadFormId',
                            bodyPadding: 20,
                            collapsible: false,
                            title: 'Speaker Picture Upload',
                            url: '/api/Account/FormData',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    title: 'Picture Required Before Submitting Sessions',
                                    items: [
                                        {
                                            xtype: 'filefield',
                                            flex: 1,
                                            border: false,
                                            height: 50,
                                            id: 'SpeakerPictureUploadXId',
                                            itemId: 'SpeakerPictureUploadId',
                                            minWidth: 150,
                                            padding: 10,
                                            fieldLabel: '',
                                            hideLabel: true,
                                            labelPad: 0
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 7,
                                            border: false,
                                            itemId: 'PicturePanelId',
                                            padding: 10,
                                            items: [
                                                {
                                                    xtype: 'image',
                                                    border: 1,
                                                    height: 150,
                                                    id: 'SpeakerImageId',
                                                    itemId: 'SpeakerImgId',
                                                    width: 150,
                                                    src: '/image/none.jpg'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});