/*
 * File: app/view/sponsor.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RegistrationApp.view.sponsor', {
    extend: 'Ext.form.Panel',
    alias: 'widget.sponsorAlias',

    itemId: 'sponsorId',
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    bodyBorder: true,
    title: 'Sponsor',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 2,
                    layout: {
                        align: 'stretch',
                        padding: 15,
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'name',
                            name: 'ContactName',
                            fieldLabel: 'Contact Name',
                            minLength: 5
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'email',
                            width: 300,
                            name: 'ContactEmail',
                            fieldLabel: 'Email'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'company',
                            name: 'Company',
                            fieldLabel: 'Company'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'phone',
                            width: 300,
                            name: 'PhoneNumber',
                            fieldLabel: 'Phone Number'
                        },
                        {
                            xtype: 'label',
                            flex: 0,
                            height: 20
                        },
                        {
                            xtype: 'checkboxgroup',
                            border: 1,
                            frame: true,
                            itemId: 'ContactMeCheckboxGroup',
                            width: 328,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            fieldLabel: '',
                            name: 'InfoWantedType',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    itemId: 'emailMeCheckbox',
                                    name: 'EmailMe',
                                    boxLabel: 'Please Email Me Information'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    itemId: 'contactMeCheckbox',
                                    name: 'ContactMe',
                                    boxLabel: 'Please Contact Me By Phone'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    itemId: 'alsoAttendingCheckBox',
                                    name: 'AlsoAttending',
                                    boxLabel: 'I Am Also Planning On Attending'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    itemId: 'sponsoredInPastCheckbox',
                                    name: 'PastSponsor',
                                    boxLabel: 'Our Company Has Previously Sponsord Code Camp'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    height: 287,
                    padding: 15,
                    layout: {
                        type: 'anchor'
                    },
                    items: [
                        {
                            xtype: 'label',
                            padding: 15,
                            text: 'Special Notes To Code Camp'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            height: 200,
                            name: 'Bio',
                            fieldLabel: ''
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    itemId: 'ToolBarForgotUsername',
                    layout: {
                        pack: 'end',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            disabled: false,
                            itemId: 'backButtonId',
                            iconAlign: 'right',
                            text: 'Back'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'continueButtonId',
                            iconAlign: 'right',
                            text: 'Continue'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});