/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.MainViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        align: 'stretch',
        type: 'hbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    id: 'LoginId',
                    bodyPadding: 10,
                    title: 'Login ',
                    url: '/api/Account/Login',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'username',
                            fieldLabel: 'Username',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            inputType: 'password',
                            name: 'password',
                            fieldLabel: 'Password',
                            allowBlank: false
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            name: 'rememberMe',
                            fieldLabel: 'Remember Me',
                            checked: true,
                            inputValue: 'true',
                            uncheckedValue: 'false'
                        },
                        {
                            xtype: 'button',
                            id: 'buttonId',
                            text: 'Login'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});