/*
 * File: app/store/StoreUsersWithLastOrderAndViewCount.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.store.StoreUsersWithLastOrderAndViewCount', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Rest',
        'App.model.ModelUsersWithLastOrderAndViewCount'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            storeId: 'storeId',
            model: 'App.model.ModelUsersWithLastOrderAndViewCount',
            proxy: {
                type: 'rest',
                url: '/rpc/Users'
            }
        }, cfg)]);
    }
});