/*
 * File: app/controller/SponsorController.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RegistrationApp.controller.SponsorController', {
    extend: 'Ext.app.Controller',

    onContinueButtonIdClick: function(button, e, eOpts) {
        var form =  Ext.ComponentQuery.query('sponsorAlias')[0].getForm();

        //debugger;
        if (form.isValid())
        {

            form.submit({
                success: function(form, action) {
                    Ext.Msg.alert('Success', action.result.msg);
                },
                failure: function(form, action) {
                    //debugger;
                    Ext.Msg.alert('Failed', action.result.msg);
                }
            });
        }


        /*
        form.submit({

        success: function(a,b,c) {
        Ext.Msg.alert("Thanks! we will get back to you asap.");   
        //  window.parent.location.href = '../../Register.aspx'; 
    },
    failure: function(a,b,c) {
        debugger;
        Ext.Msg.alert("hmm.  Something seems to have gone wrong.  Please email sponsorship@siliconvalley-codecamp.com for information.");   
        // window.parent.location.href = '../../Register.aspx'; 
    }

});
*/
    },

    onBackButtonIdClick: function(button, e, eOpts) {
        var tabWizardPanel = Ext.getCmp('TabWizardId');
        tabWizardPanel.setActiveTab(tabWizardPanel.getTabIdByName('AttendeeSpeakerSponsorId'));
    },

    init: function(application) {
        this.control({
            "sponsorAlias #continueButtonId": {
                click: this.onContinueButtonIdClick
            },
            "sponsorAlias #backButtonId": {
                click: this.onBackButtonIdClick
            }
        });
    }

});
