/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'button',
                            id: 'buttonId',
                            itemId: 'buttonItemId',
                            text: 'hits controller'
                        },
                        {
                            xtype: 'button',
                            text: 'Does Compent Query of buttonId',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {

        var componentQueryButtonIdLen = Ext.ComponentQuery.query('#buttonId').length; 
        // returns 0

        var componentQueryButtonItemIdLen = Ext.ComponentQuery.query('#buttonItemId').length;
        // returns 1

        alert(componentQueryButtonIdLen + ',' + componentQueryButtonItemIdLen);


    }

});