/*
 * File: app/model/SessionsModel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.SessionsModel', {
    extend: 'Ext.data.Model',

    config: {
        idProperty: 'Id',
        fields: [
            {
                name: 'CodeCampYearId'
            },
            {
                name: 'Attendeesid'
            },
            {
                name: 'Title'
            },
            {
                name: 'Description'
            },
            {
                name: 'InterestedCount'
            },
            {
                name: 'WillAttendCount'
            },
            {
                name: 'PresenterName'
            },
            {
                name: 'RoomNumber'
            },
            {
                name: 'SessionTime'
            },
            {
                name: 'PresenterUrl'
            },
            {
                name: 'SpeakerPictureUrl'
            },
            {
                name: 'Id'
            }
        ],
        proxy: {
            type: 'ajax',
            url: '../GeneralHandlers/Sessions.ashx?CodeCampYearId=6',
            reader: {
                type: 'json',
                idProperty: 'Id',
                rootProperty: 'rows'
            }
        }
    }
});