/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.MainViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    items: [
                        {
                            xtype: 'form',
                            id: 'mailGeneratorFormPanelId',
                            padding: '5 5 5 5',
                            bodyPadding: '5 5 5 5',
                            title: 'Mail Generator',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'GenerateEmailButtonId',
                                            text: 'Generate'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'previewLetterButtonId',
                                            text: 'Preview Letter'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'previewEmailToId',
                                            width: 332,
                                            name: 'previewEmailSend',
                                            value: 'peter@peterkellner.net',
                                            fieldLabel: 'Send Preview To'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'emailUrl',
                                    value: 'http://pkellner.site44.com/',
                                    fieldLabel: 'URL Of Letter',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'subject',
                                    fieldLabel: 'Subject',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'htmleditor',
                                    anchor: '100%',
                                    height: 150,
                                    style: 'background-color: white;',
                                    name: 'emailHtml',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    height: 230,
                                    margin: '30 0 0 0',
                                    name: 'sqlStatement',
                                    value: 'select id from attendees where id > 6000',
                                    fieldLabel: 'Sql Statement',
                                    allowBlank: false
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Admin Users',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'GridPanelAdminUsersId',
                                    store: 'StoreAdminUsers',
                                    viewConfig: {

                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 181,
                                            dataIndex: 'username',
                                            text: 'Username'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'roles',
                                            flex: 1,
                                            text: 'Roles'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'ReLoadAdminUsersButton',
                                                    text: 'ReLoadGrid'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});